Type = "jscript"
Intro = "解决Hell绝大部分需求的机器人"
Desc = "Hell综合脚本机器人"
OnOpen = "onOpen"
OnClose = "onClose"
OnConnect = "onConnected"
OnDisconnect = "onDisconnected"
OnBroadcast = "onBroadcast"
OnAssist = "onAssist"
OnBuffer = "onBuffer"
OnBufferMin = 2
OnBufferMax = 0
Channel = "zsz-self.jvs"
[[RequiredParams]]
  Name = "passw"
  Desc = "密码"
  Intro = "游戏密码"
[[RequiredParams]]
  Name = "id"
  Desc = "帐号ID"
  Intro = "****很重要，自己ID的英文名字"
[[RequiredParams]]
  Name = "num_cmds"
  Desc = "每心跳命令数"
  Intro = "每心跳内输出最多几个命令（偶数，可以围绕46上下调整，数值越大，越容易被雷劈）"
[[RequiredParams]]
  Name = "id_weapon"
  Desc = "武器装备英文名（非必填）"
  Intro = ""

[[RequiredParams]]
  Name = "id_weapon2"
  Desc = "备用武器装备英文名（非必填）"
  Intro = ""

[[RequiredParams]]
  Name = "id_weapon3"
  Desc = "额外维修装备列表"
  Intro = "分号分割的额外维修装备列表，如 armor;staff"
[[RequiredParams]]
  Name = "cmd_pfm"
  Desc = "主绝招"
  Intro = "主绝招" 
[[RequiredParams]]
  Name = "house"
  Desc = "房屋信息"
  Intro = "设置后会将1933-1949设置为对应的房屋信息\n格式为'包子铺 bzp 1558'"
[[RequiredParams]]
  Name = "list_mloc"
  Desc = "Miss坐标列表"
  Intro = "  MISS武器的坐标（举例：yyyy:1150,oooo:1956,zwca:1202）\n  会自动添加到地图内，地图内不需要设置\n  "
[[Triggers]]
  ID = "gap"
  Name = "gap"
  Enabled = true
  Match = "^> $"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = ""
  SendTo = 0
  Sequence = 1
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = true
  OmitFromOutput = true
  Inverse = false
  Italic = false
  Variable = ""
  [[Triggers]]
  ID = "line"
  Name = "line"
  Enabled = true
  Match = "*"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnLine"
  SendTo = 0
  Sequence = 1
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
  [[Triggers]]
  ID = "room_exits"
  Name = "room_exits"
  Enabled = true
  Match = "^    这里(唯一的出口是|明显的出口是)(.*)。$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnRoomExits"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "room_noexit"
  Name = "room_noexit"
  Enabled = true
  Match = "^    这里(没有)任何明显的出路。()$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnRoomExits"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

  [[Triggers]]
  ID = "room_obj"
  Name = "room_obj"
  Enabled = false
  Match = "^  (.+)\\((.+)\\).*$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnRoomObj"
  SendTo = 0
  Sequence = 499
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "roomobj"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
    [[Triggers]]
  ID = "room_objend"
  Name = "room_objend"
  Enabled = false
  Match = "^(.*)$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnRoomObjEnd"
  SendTo = 0
  Sequence = 500
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "roomobj"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

  [[Triggers]]
  ID = "item"
  Name = "item"
  Enabled = true
  Match = "^你身上带著下列这些东西\\(负重\\s*(\\d+)%\\)：$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnItem"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
  [[Triggers]]
  ID = "itemobj"
  Name = "itemobj"
  Enabled = false
  Match = "^(  |□)(.*)\\((.*)\\)$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnItemObj"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "item"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
  [[Triggers]]
  ID = "itemobjend"
  Name = "itemobjend"
  Enabled = false
  Match = "^目前携带了.+件物品。$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnItemObjEnd"
  SendTo = 0
  Sequence = 500
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "item"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
[[Triggers]]
  ID = "item_noitem"
  Name = "item_noitem"
  Enabled = true
  Match = "^目前你身上没有任何东西。$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnItemNoItem"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
