Type = "jscript"
Intro = "解决Hell绝大部分需求的机器人"
Desc = "Hell综合脚本机器人"
OnOpen = "onOpen"
OnClose = "onClose"
OnConnect = "onConnected"
OnDisconnect = "onDisconnected"
OnBroadcast = "onBroadcast"
OnAssist = "onAssist"
OnBuffer = "onBuffer"
OnBufferMin = 2
OnBufferMax = 0
Channel = "zsz-self.jvs"
[[RequiredParams]]
  Name = "passw"
  Desc = "密码"
  Intro = "游戏密码"
[[RequiredParams]]
  Name = "id"
  Desc = "帐号ID"
  Intro = "****很重要，自己ID的英文名字"
[[RequiredParams]]
  Name = "id_pass"
  Desc = "门派缩写"
  Intro = "门派缩写（有密道的门派要填）"

[[RequiredParams]]
  Name = "id_weapon"
  Desc = "武器装备英文名（非必填）"
  Intro = ""

[[RequiredParams]]
  Name = "id_weapon2"
  Desc = "备用武器装备英文名（非必填）"
  Intro = ""

[[RequiredParams]]
  Name = "id_weapon3"
  Desc = "额外维修装备列表"
  Intro = "分号分割的额外维修装备列表，如 armor;staff"
[[RequiredParams]]
  Name = "cmd_pfm"
  Desc = "主绝招"
  Intro = "主绝招" 
[[RequiredParams]]
  Name = "house"
  Desc = "房屋信息"
  Intro = "设置后会将1933-1949设置为对应的房屋信息\n格式为'包子铺 bzp 1558'"
[[RequiredParams]]
  Name = "list_mloc"
  Desc = "Miss坐标列表"
  Intro = "  MISS武器的坐标（举例：yyyy:1150,oooo:1956,zwca:1202）\n  会自动添加到地图内，地图内不需要设置\n  "
[[Triggers]]
  ID = "gap"
  Name = "gap"
  Enabled = true
  Match = "^> $"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = ""
  SendTo = 0
  Sequence = 1
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = true
  OmitFromOutput = true
  Inverse = false
  Italic = false
  Variable = ""
  [[Triggers]]
  ID = "leave"
  Name = "leave"
  Enabled = true
  Match = "^(你赶着镖车往.+驶去。)$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = ""
  SendTo = 0
  Sequence = 9
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = true
  OmitFromOutput = true
  Inverse = false
  Italic = false
  Variable = ""
  [[Triggers]]
  ID = "line"
  Name = "line"
  Enabled = true
  Match = "*"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnLine"
  SendTo = 0
  Sequence = 10
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
  [[Triggers]]
  ID = "room_exits"
  Name = "room_exits"
  Enabled = true
  Match = "^    这里(唯一的出口是|明显的出口是)(.*)。$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnRoomExits"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "room_noexit"
  Name = "room_noexit"
  Enabled = true
  Match = "^    这里(没有)任何明显的出路。()$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnRoomExits"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

  [[Triggers]]
  ID = "room_obj"
  Name = "room_obj"
  Enabled = false
  Match = "^  (.+)\\((.+)\\).*$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnRoomObj"
  SendTo = 0
  Sequence = 499
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "roomobj"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
    [[Triggers]]
  ID = "room_objend"
  Name = "room_objend"
  Enabled = false
  Match = "^(.*)$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnRoomObjEnd"
  SendTo = 0
  Sequence = 500
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "roomobj"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

  [[Triggers]]
  ID = "item"
  Name = "item"
  Enabled = true
  Match = "^你身上带著下列这些东西\\(负重\\s*(\\d+)%\\)：$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnItem"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
  [[Triggers]]
  ID = "itemobj"
  Name = "itemobj"
  Enabled = false
  Match = "^(  |□)(.*)\\((.*)\\)$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnItemObj"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "item"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
  [[Triggers]]
  ID = "itemobjend"
  Name = "itemobjend"
  Enabled = false
  Match = "^目前携带了.+件物品。$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnItemObjEnd"
  SendTo = 0
  Sequence = 500
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "item"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
[[Triggers]]
  ID = "item_noitem"
  Name = "item_noitem"
  Enabled = true
  Match = "^目前你身上没有任何东西。$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnItemNoItem"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
[[Triggers]]
  ID = "core_response"
  Name = "core_response"
  Enabled = true
  Match = "^设定环境变数：no_more = \"([^-]+)-([^=]+)(=(.*)){0,1}\"$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnResponse"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
[[Triggers]]
  ID = "login"
  Name = "login"
  Enabled = true
  Match = "^目前共有 .+ 位巫师、.+ 位玩家在线上，以及 .+ 位使用者尝试连线中。$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnConnectLogin"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
  [[Triggers]]
  ID = "busy_end"
  Name = "busy_end"
  Enabled = false
  Match = "^(> )*(你要花多少精修行？|你吐纳完毕，睁开双眼，站了起来。)$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnBusyEnd"
  SendTo = 0
  Sequence = 50
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "busy"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
  [[Triggers]]
  ID = "move_retry"
  Name = "move_retry"
  Enabled = false
  Match = "^(> )*(只听得江面上隐隐传来：“别急嘛，这儿正忙着呐……”|你现在正忙着哩。|你手忙脚乱的折腾了半天，可是大车一动不动。|你上一个动作还没有完成，先等等吧。)$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnMoveRetry"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "move"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
  [[Triggers]]
  ID = "move_getout"
  Name = "move_getout"
  Enabled = false
  Match = "^(> )*(艄公说“到啦，上岸吧”，随即把一块踏脚板搭上堤岸。)$"
  Send = "halt;look"
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = ""
  SendTo = 10
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "move"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""  
[[Triggers]]
  ID = "move_enterboat"
  Name = "move_enterboat"
  Enabled = false
  Match = "^(> )*(一叶扁舟缓缓地驶了过来，|一尾小舟缓缓地驶了过来，|岸边一只渡船上的艄公说道：|岸边一只渡船上的老艄公说道：|湖畔一尾小舟上一个绿衫少女细声说到：|岸边一只小舟上的老艄公说道：)"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnMoveEnterBoat"
  SendTo = 0
  Sequence = 70
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "move"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
[[Timers]]
  ID = "steptimeout"
  Name = "steptimeout"
  Enabled = false
  Hour = 0
  Minute = 0
  Second = 1.0
  Send = ""
  Script = "App.OnMoveStepTimeout"
  AtTime = false
  SendTo = 0
  ActionWhenDisconnectd = false
  Temporary = false
  OneShot = false
  Group = ""
  Variable = ""
  OmitFromLog = false
  OmitFromOutput = false
[[Timers]]
  ID = "busy_retry"
  Name = "busy_retry"
  Enabled = false
  Hour = 0
  Minute = 0
  Second = 1.0
  Send = ""
  Script = "App.Core.OnBusyRetry"
  AtTime = false
  SendTo = 0
  ActionWhenDisconnectd = false
  Temporary = false
  OneShot = false
  Group = ""
  Variable = ""
  OmitFromLog = false
  OmitFromOutput = false
[[Aliases]]
  ID = "queue"
  Name = "queue"
  Enabled = true
  Match = "^#(do|delay|to) .*$"
  Send = ""
  Script = "App.Core.OnAliasQueue"
  SendTo = 0
  Sequence = 0
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Group = ""
  IgnoreCase = false
  KeepEvaluating = false
  Menu = false
  OmitFromLog = false
  Variable = ""
  ReverseSpeedwalk = false
  OmitFromOutput = false
  OmitFromCommandHistory = false
[[Aliases]]
  ID = "queue2"
  Name = "queue2"
  Enabled = true
  Match = "^#(afterbusy)(\\|.*){0,1}$"
  Send = ""
  Script = "App.Core.OnAliasQueue"
  SendTo = 0
  Sequence = 0
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Group = ""
  IgnoreCase = false
  KeepEvaluating = false
  Menu = false
  OmitFromLog = false
  Variable = ""
  ReverseSpeedwalk = false
  OmitFromOutput = false
  OmitFromCommandHistory = false
  [[Aliases]]
  ID = "stop"
  Name = "stop"
  Enabled = true
  Match = "^#stop$"
  Send = ""
  Script = "App.Core.OnAliasStop"
  SendTo = 0
  Sequence = 0
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Group = ""
  IgnoreCase = false
  KeepEvaluating = false
  Menu = false
  OmitFromLog = false
  Variable = ""
  ReverseSpeedwalk = false
  OmitFromOutput = false
  OmitFromCommandHistory = false
   [[Aliases]]
  ID = "item"
  Name = "item"
  Enabled = true
  Match = "^#item (.+)$"
  Send = ""
  Script = "App.Core.OnAliasItem"
  SendTo = 0
  Sequence = 0
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Group = ""
  IgnoreCase = false
  KeepEvaluating = false
  Menu = false
  OmitFromLog = false
  Variable = ""
  ReverseSpeedwalk = false
  OmitFromOutput = false
  OmitFromCommandHistory = false
  